/** Buy or sell side of the book. */
export enum Side {
  BUY = 'buy',
  SELL = 'sell',
}

/** Supported order types. */
export enum OrderType {
  LIMIT = 'limit',
  MARKET = 'market',
}

/**
 * Time-in-force policies.
 * - GTC: rest on the book until filled or cancelled
 * - IOC: fill immediately, cancel any unfilled remainder
 * - FOK: fill entirely immediately or cancel the whole order
 */
export enum TimeInForce {
  GTC = 'GTC',
  IOC = 'IOC',
  FOK = 'FOK',
}

export interface CreateLimitOrderParams {
  id: string;
  side: Side;
  size: number;
  price: number;
  timeInForce?: TimeInForce;
  postOnly?: boolean;
}

export interface CreateMarketOrderParams {
  side: Side;
  size: number;
  /** Optional client order id for tracking; not rested on the book. */
  id?: string;
}

export interface ModifyOrderParams {
  size?: number;
  price?: number;
}

/** Aggregated depth at a single price level. */
export interface PriceLevel {
  price: number;
  size: number;
  orders: number;
}

/** A single fill / trade generated by the matcher. */
export interface Trade {
  id: string;
  takerOrderId: string;
  makerOrderId: string;
  price: number;
  size: number;
  side: Side;
  timestamp: number;
}

/** Snapshot of a resting (or fully filled) order for API responses. */
export interface OrderSnapshot {
  id: string;
  side: Side;
  price: number;
  size: number;
  originalSize: number;
  timeInForce: TimeInForce;
  timestamp: number;
}

export interface OrderResult {
  /** Orders that were fully filled during matching (makers + taker if fully filled). */
  done: OrderSnapshot[];
  /** Remaining size of a partially filled order (maker that stayed, or IOC leftover cancelled). */
  partial: OrderSnapshot | null;
  /** Quantity filled against the incoming (taker) order. */
  quantityFilled: number;
  /** Quantity that could not be filled (for market / IOC leftovers). */
  quantityLeft: number;
  /** Executed trades in time order. */
  trades: Trade[];
}
